spring:
  application:
    name: CARENATION_PROJECT
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.carenation.carenation_project.dto
  configuration:
    map-underscore-to-camel-case: true